DEFAULT_AC_VIDEO_JEPA_MODEL_CONFIG = {
    "model_type": "ac_video_jepa",
    "encoder": {
        "encoder_type": "impala",
        "width": 1,
        "stack_sizes": [16, 32, 32],
        "num_blocks": 2,
        "dropout_rate": None,
        "layer_norm": False,
        "input_channels": 2,
        "final_ln": True,
        "mlp_output_dim": 512,
        "input_shape": [2, 64, 64],
    },
    "action_encoder": {
        "action_encoder_type": "identity",
    },
    "predictor": {
        "predictor_type": "rnn",
        "hidden_size": None,
        "action_dim": 2,
        "num_layers": 1,
        "use_encoder_final_ln": True,
    },
    "projector": {
        "enabled": False,
        "mlp_spec": None,
        "hidden_multiplier": 4,
    },
    "inverse_dynamics_model": {
        "enabled": True,
        "hidden_dim": 256,
        "action_dim": 2,
    },
    "regularizer": {
        "regularizer_type": "vc_idm_sim",
        "cov_coeff": 8.0,
        "std_coeff": 16.0,
        "sim_coeff_t": 12.0,
        "idm_coeff": 1.0,
        "std_margin": 1.0,
        "first_t_only": False,
        "spatial_as_samples": False,
        "sim_t_after_proj": False,
        "idm_after_proj": False,
    },
    "prediction_cost": {
        "prediction_cost_type": "square_loss_seq",
        "use_projector": False,
    },
}
