set_type: tse
strict: true
metric_to_input_names: null
metrics:
  snr:
    zero_mean: false
    reduction: mean
  sisdr:
    zero_mean: false
    reduction: mean
  sdsdr:
    mu: 1.0
    eps: 1.0e-8
    reduction: mean
  dtw:
    reduction: mean
    use_pruning: true
  lp_error:
    p: 2.0
    reduction: mean
  sisir:
    eps: 1.0e-8
    reduction: mean
  sisar:
    eps: 1.0e-8
    reduction: mean
  lsd:
    n_fft: 512
    hop_length: null
    win_length: null
    window: hann
    center: true
    normalized: false
    onesided: true
    eps: 1.0e-8
    reduction: mean
  spectral_kl:
    n_fft: 512
    hop_length: null
    win_length: null
    window: hann
    center: true
    normalized: false
    onesided: true
    eps: 1.0e-8
    reduction: mean
    normalize: true
  itakura_saito:
    n_fft: 512
    hop_length: null
    win_length: null
    window: hann
    center: true
    normalized: false
    onesided: true
    eps: 1.0e-8
    reduction: mean
  stoi:
    sample_rate: 16000
    reduction: mean
  estoi:
    sample_rate: 16000
    reduction: mean
  pesq:
    sample_rate: 16000
    mode: wb
    reduction: mean
  dnsmos_p808:
    sample_rate: 16000
    personalized: false
    device: null
    num_threads: null
    cache_session: true
    reduction: mean
  dnsmos_p835:
    sample_rate: 16000
    personalized: false
    device: null
    num_threads: null
    cache_session: true
    reduction: mean
  dnsmos_sig:
    sample_rate: 16000
    personalized: false
    device: null
    num_threads: null
    cache_session: true
    reduction: mean
  dnsmos_bak:
    sample_rate: 16000
    personalized: false
    device: null
    num_threads: null
    cache_session: true
    reduction: mean
  dnsmos_ovrl:
    sample_rate: 16000
    personalized: false
    device: null
    num_threads: null
    cache_session: true
    reduction: mean