set_type: tse
strict: true
metric_to_input_names: null
metrics:
  snr:
    zero_mean: false
    reduction: mean
  sisdr:
    zero_mean: false
    reduction: mean
  sdsdr:
    mu: 1.0
    eps: 1.0e-8
    reduction: mean
  lp_error:
    p: 2.0
    reduction: mean