default:
  strict: true

  datasets:
    train: train_dataset.yaml
    val: val_dataset.yaml
    test: test_dataset.yaml

  collators:
    train: collator_train.yaml
    val: collator_val.yaml
    test: collator_test.yaml

  dataloader_configs:
    train:
      batch_size: 2
      shuffle: true
      num_workers: 0
      pin_memory: false
      drop_last: true

    val:
      batch_size: 2
      shuffle: false
      num_workers: 0
      pin_memory: false
      drop_last: false

    test:
      batch_size: 2
      shuffle: false
      num_workers: 0
      pin_memory: false
      drop_last: false